import { describe, it, expect, vi } from "vitest";
import {
  detectPlatform,
  extractAssistantBlobs,
  formatTurnSummary,
  parsePrUrl,
} from "../src/agent.js";
import { formatMetricsMarkdown } from "../src/metrics.js";
import type { ReviewMetrics } from "../src/types.js";

// Mock the exec module at the module level
let capturedArgs: string[] = [];
vi.mock("../src/utils/exec.js", () => ({
  exec: vi.fn(async (_cmd: string, args: string[]) => {
    capturedArgs = args;
    return { stdout: "", stderr: "" };
  }),
  execJson: vi.fn(async () => ({})),
}));

describe("detectPlatform", () => {
  it.each([
    ["https://github.com/foo/bar/pull/42", "github"],
    ["https://gitlab.com/foo/bar/-/merge_requests/3", "gitlab"],
    ["https://gitlab.example.dev/group/repo/-/merge_requests/19", "gitlab"],
  ] as const)("detects platform for %s", (url, expected) => {
    expect(detectPlatform(url)).toBe(expected);
  });

  it("throws on unrecognized platform", () => {
    expect(() => detectPlatform("https://bitbucket.org/foo/bar/pull-requests/1")).toThrow(
      /Cannot detect platform/,
    );
  });
});

describe("parsePrUrl", () => {
  it("parses GitHub PR URL", () => {
    const result = parsePrUrl("https://github.com/octo/hoDor/pull/123");
    expect(result.owner).toBe("octo");
    expect(result.repo).toBe("hoDor");
    expect(result.prNumber).toBe(123);
    expect(result.host).toBe("github.com");
  });

  it("parses GitLab MR URL with subgroups", () => {
    const url =
      "https://gitlab.example.com/org/security/tools/hodor/-/merge_requests/99";
    const result = parsePrUrl(url);
    expect(result.owner).toBe("org/security/tools");
    expect(result.repo).toBe("hodor");
    expect(result.prNumber).toBe(99);
    expect(result.host).toBe("gitlab.example.com");
  });

  it("throws on invalid URL", () => {
    expect(() => parsePrUrl("https://gitlab.com/foo/bar/issues/1")).toThrow();
  });

  it("throws on non-numeric PR number", () => {
    expect(() => parsePrUrl("https://github.com/foo/bar/pull/abc")).toThrow(
      /Invalid PR number/,
    );
  });

  it("throws on non-numeric MR number", () => {
    expect(() =>
      parsePrUrl("https://gitlab.com/foo/bar/-/merge_requests/xyz"),
    ).toThrow(/Invalid MR number/);
  });
});

describe("formatMetricsMarkdown", () => {
  it("includes expected fields", () => {
    const metrics: ReviewMetrics = {
      inputTokens: 1000,
      outputTokens: 80,
      cacheReadTokens: 900,
      cacheWriteTokens: 0,
      totalTokens: 1080,
      cost: 1.2345,
      turns: 3,
      toolCalls: 8,
      durationSeconds: 125,
    };

    const markdown = formatMetricsMarkdown(metrics);

    expect(markdown).toContain("**Review Metrics**");
    expect(markdown).toContain("3 turns");
    expect(markdown).toContain("8 tool calls");
    expect(markdown).toContain("2m 5s");
    expect(markdown).toContain("in `1.0K`");
    expect(markdown).toContain("cached `900`");
    expect(markdown).toContain("out `80`");
    expect(markdown).toContain("Cost: `$1.2345`");
  });

  it("omits cache when zero", () => {
    const metrics: ReviewMetrics = {
      inputTokens: 500,
      outputTokens: 100,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      totalTokens: 600,
      cost: 0,
      turns: 1,
      toolCalls: 2,
      durationSeconds: 30,
    };

    const markdown = formatMetricsMarkdown(metrics);

    expect(markdown).not.toContain("cached");
    expect(markdown).not.toContain("Cost");
  });
});

describe("postReviewComment", () => {
  it("appends model and metrics footer", async () => {
    // postReviewComment uses the mocked exec from module level
    const { postReviewComment } = await import("../src/agent.js");

    const result = await postReviewComment({
      prUrl: "https://github.com/foo/bar/pull/42",
      reviewText: "Review body",
      model: "openai/gpt-5",
      metricsFooter: "**Review Metrics**\n- Total: `123`",
    });

    expect(result.success).toBe(true);
    const bodyIndex = capturedArgs.indexOf("--body");
    const capturedBody = bodyIndex >= 0 ? capturedArgs[bodyIndex + 1] : "";
    expect(capturedBody).toContain(
      "Review generated by Hodor (model: `openai/gpt-5`)",
    );
    expect(capturedBody).toContain("**Review Metrics**");
  });
});

describe("extractAssistantBlobs", () => {
  const assistantMessage = {
    role: "assistant",
    content: [
      { type: "thinking", thinking: "Inspect diff first." },
      { type: "text", text: "I am going to inspect the worker changes." },
      { type: "toolCall", name: "read", arguments: { path: "foo.ts" } },
      { type: "text", text: "I now have enough context to check error handling." },
    ],
    stopReason: "toolUse",
  };

  it("extracts completed text blobs", () => {
    expect(extractAssistantBlobs(assistantMessage, "text")).toEqual([
      "I am going to inspect the worker changes.",
      "I now have enough context to check error handling.",
    ]);
  });

  it("extracts completed thinking blobs", () => {
    expect(extractAssistantBlobs(assistantMessage, "thinking")).toEqual([
      "Inspect diff first.",
    ]);
  });

  it("ignores non-assistant messages", () => {
    expect(
      extractAssistantBlobs(
        { role: "toolResult", content: [{ type: "text", text: "Done" }] },
        "text",
      ),
    ).toEqual([]);
  });
});

describe("formatTurnSummary", () => {
  it("includes stop reason, tool result count, and text blob count", () => {
    const summary = formatTurnSummary(
      {
        role: "assistant",
        content: [{ type: "text", text: "Checking the diff." }],
        stopReason: "toolUse",
      },
      [{ role: "toolResult" }, { role: "toolResult" }],
    );

    expect(summary).toBe("stop=toolUse, tool_results=2, text_blobs=1");
  });

  it("reports no assistant output when the turn has no assistant message", () => {
    expect(formatTurnSummary({ role: "toolResult", content: [] }, [])).toBe(
      "no assistant output",
    );
  });
});
