import hashlib
from unittest.mock import patch, MagicMock

import pytest

from hodor.agent import detect_platform, parse_pr_url, _compute_diff_hash, _extract_diff_hash


@pytest.mark.parametrize(
    "url,expected",
    [
        ("https://github.com/foo/bar/pull/42", "github"),
        ("https://gitlab.com/foo/bar/-/merge_requests/3", "gitlab"),
        ("https://gitlab.example.dev/group/repo/-/merge_requests/19", "gitlab"),
    ],
)
def test_detect_platform(url, expected):
    assert detect_platform(url) == expected


def test_parse_pr_url_github():
    owner, repo, number, host = parse_pr_url("https://github.com/octo/hoDor/pull/123")
    assert owner == "octo"
    assert repo == "hoDor"
    assert number == 123
    assert host == "github.com"


def test_parse_pr_url_gitlab_subgroups():
    url = "https://gitlab.example.com/org/security/tools/hodor/-/merge_requests/99"
    owner, repo, number, host = parse_pr_url(url)
    assert owner == "org/security/tools"
    assert repo == "hodor"
    assert number == 99
    assert host == "gitlab.example.com"


def test_parse_pr_url_invalid():
    with pytest.raises(ValueError):
        parse_pr_url("https://gitlab.com/foo/bar/issues/1")


# --- _extract_diff_hash tests ---


def test_extract_diff_hash_present():
    body = (
        "Some review text\n\n---\n\n"
        "*Review generated by Hodor using `some-model`*\n"
        "<!-- hodor:diff-hash:sha256:abcdef1234567890 -->"
    )
    assert _extract_diff_hash(body) == "abcdef1234567890"


def test_extract_diff_hash_missing():
    body = "Some review text\n\n---\n\n*Review generated by Hodor using `some-model`*"
    assert _extract_diff_hash(body) is None


def test_extract_diff_hash_empty():
    assert _extract_diff_hash("") is None


# --- _compute_diff_hash tests ---


@patch("hodor.agent.subprocess.run")
def test_compute_diff_hash_with_diff_base_sha(mock_run):
    diff_content = "diff --git a/foo.py b/foo.py\n+hello\n"
    mock_run.return_value = MagicMock(returncode=0, stdout=diff_content)

    from pathlib import Path
    result = _compute_diff_hash(Path("/tmp/workspace"), "abc123", "main")

    assert result == hashlib.sha256(diff_content.encode()).hexdigest()
    mock_run.assert_called_once_with(
        ["git", "diff", "abc123", "HEAD"],
        capture_output=True, text=True, cwd="/tmp/workspace",
    )


@patch("hodor.agent.subprocess.run")
def test_compute_diff_hash_falls_back_to_target_branch(mock_run):
    diff_content = "diff --git a/bar.py b/bar.py\n+world\n"
    mock_run.return_value = MagicMock(returncode=0, stdout=diff_content)

    from pathlib import Path
    result = _compute_diff_hash(Path("/tmp/workspace"), None, "develop")

    assert result == hashlib.sha256(diff_content.encode()).hexdigest()
    mock_run.assert_called_once_with(
        ["git", "diff", "origin/develop", "HEAD"],
        capture_output=True, text=True, cwd="/tmp/workspace",
    )


@patch("hodor.agent.subprocess.run")
def test_compute_diff_hash_returns_empty_on_failure(mock_run):
    mock_run.return_value = MagicMock(returncode=128, stdout="")

    from pathlib import Path
    result = _compute_diff_hash(Path("/tmp/workspace"), None, "main")

    assert result == ""


@patch("hodor.agent.subprocess.run")
def test_compute_diff_hash_consistent(mock_run):
    """Same diff content should always produce the same hash."""
    diff_content = "diff --git a/x.py b/x.py\n+consistent\n"
    mock_run.return_value = MagicMock(returncode=0, stdout=diff_content)

    from pathlib import Path
    hash1 = _compute_diff_hash(Path("/tmp/w1"), "sha1", "main")
    hash2 = _compute_diff_hash(Path("/tmp/w2"), "sha2", "main")

    assert hash1 == hash2
