import { createHash } from "node:crypto";
import { exec } from "./utils/exec.js";
import { logger } from "./utils/logger.js";
import { relativizeWorkspacePath } from "./utils/path.js";
import { postGiteaPrComment } from "./gitea.js";
import {
  bulkPublishGitlabDraftNotes,
  createGitlabDraftNote,
  getGitlabMrDiffRefs,
  HODOR_REVIEW_MARKER,
  listHodorDiscussions,
  postGitlabCommitStatus,
  postGitlabMrComment,
  resolveGitlabDiscussions,
  type DiffRefs,
} from "./gitlab.js";
import { detectPlatform, parsePrUrl } from "./platform.js";
import { renderMarkdown, renderSummaryMarkdown } from "./render.js";
import type {
  ParsedPrUrl,
  PostCommentResult,
  ReviewFinding,
  ReviewOutput,
} from "./types.js";

const FINDING_MARKER_RE = /<!--\s*hodor:finding:([a-f0-9]{64})\s*-->/i;

export function getFindingFingerprint(
  finding: ReviewFinding,
  workspacePath?: string | null,
): string {
  const path = relativizeWorkspacePath(
    finding.code_location.absolute_file_path,
    workspacePath ?? undefined,
  );
  const title = finding.title.replace(/^\[P[0-3]\]\s*/, "").trim().toLowerCase();
  return createHash("sha256").update(`${path}\n${title}`).digest("hex");
}

function getDiscussionFingerprint(body: string): string | null {
  return body.match(FINDING_MARKER_RE)?.[1]?.toLowerCase() ?? null;
}

export async function postGitlabReviewCommitStatus(
  parsed: ParsedPrUrl,
  review: ReviewOutput,
  diffRefs: DiffRefs,
): Promise<void> {
  const blocking = review.findings.filter((finding) => finding.priority <= 1).length;
  const state = blocking > 0 ? "failed" : "success";
  const description =
    blocking > 0
      ? `${blocking} blocking issue(s) found`
      : review.findings.length > 0
        ? `${review.findings.length} non-blocking issue(s)`
        : "No issues found";

  await postGitlabCommitStatus(
    parsed.owner,
    parsed.repo,
    diffRefs.head_sha,
    state,
    parsed.host,
    { description },
  );
}

export async function postReviewComment(opts: {
  prUrl: string;
  reviewText: string;
  model?: string | null;
  metricsFooter?: string | null;
  headSha?: string | null;
}): Promise<PostCommentResult> {
  const { prUrl, reviewText, model, metricsFooter, headSha } = opts;
  const platform = detectPlatform(prUrl);
  const parsed = parsePrUrl(prUrl);
  let body = reviewText;

  if (headSha) body = `<!-- hodor:sha:${headSha} -->\n${body}`;
  if (model) body += `\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
  if (metricsFooter) body += `\n\n${metricsFooter}`;

  try {
    if (platform === "github") {
      await exec("gh", [
        "pr",
        "review",
        String(parsed.prNumber),
        "--repo",
        `${parsed.owner}/${parsed.repo}`,
        "--comment",
        "--body",
        body,
      ]);
      return { success: true, platform, prNumber: parsed.prNumber };
    }
    if (platform === "gitea") {
      await postGiteaPrComment(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        body,
        parsed.host,
      );
      return { success: true, platform, prNumber: parsed.prNumber };
    }

    await postGitlabMrComment(
      parsed.owner,
      parsed.repo,
      parsed.prNumber,
      body,
      parsed.host,
    );
    return {
      success: true,
      platform,
      mrNumber: parsed.prNumber,
      summaryPosted: true,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to post comment: ${message}`);
    return { success: false, platform, error: message };
  }
}

export async function postReviewStructured(opts: {
  prUrl: string;
  review: ReviewOutput;
  model?: string | null;
  metricsFooter?: string | null;
  reviewStyle?: "summary" | "inline" | "hybrid";
  commitStatus?: boolean;
  headSha?: string | null;
  workspacePath?: string | null;
  reconcileDiscussions?: boolean;
}): Promise<PostCommentResult> {
  const {
    prUrl,
    review,
    model,
    metricsFooter,
    reviewStyle = "hybrid",
    commitStatus = false,
    headSha,
    workspacePath,
    reconcileDiscussions = false,
  } = opts;

  const platform = detectPlatform(prUrl);
  if (platform !== "gitlab" || reviewStyle === "summary") {
    return postReviewComment({
      prUrl,
      reviewText: renderMarkdown(review),
      model,
      metricsFooter,
      headSha,
    });
  }

  const parsed = parsePrUrl(prUrl);
  const errors: string[] = [];
  let diffRefs: DiffRefs;
  try {
    diffRefs = await getGitlabMrDiffRefs(
      parsed.owner,
      parsed.repo,
      parsed.prNumber,
      parsed.host,
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.warn(`Failed to get diff_refs, falling back to summary mode: ${message}`);
    return postReviewComment({
      prUrl,
      reviewText: renderMarkdown(review),
      model,
      metricsFooter,
      headSha,
    });
  }

  const existingByFingerprint = new Map<string, Set<string>>();
  try {
    const discussions = await listHodorDiscussions(
      parsed.owner,
      parsed.repo,
      parsed.prNumber,
      parsed.host,
    );
    for (const discussion of discussions) {
      if (discussion.resolved) continue;
      const fingerprint = getDiscussionFingerprint(discussion.body);
      if (!fingerprint) continue;
      const ids = existingByFingerprint.get(fingerprint) ?? new Set<string>();
      ids.add(discussion.discussionId);
      existingByFingerprint.set(fingerprint, ids);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (reconcileDiscussions) {
      errors.push(`discussion listing: ${message}`);
    }
    logger.warn(`Failed to list open Hodor discussions for deduplication: ${message}`);
  }

  let inlineCreated = 0;
  let inlineFailed = 0;
  let inlineDeduplicated = 0;
  for (const finding of review.findings) {
    const fingerprint = getFindingFingerprint(finding, workspacePath);
    if (existingByFingerprint.has(fingerprint)) {
      inlineDeduplicated++;
      continue;
    }

    const relPath = relativizeWorkspacePath(
      finding.code_location.absolute_file_path,
      workspacePath ?? undefined,
    );
    const title = /^\[P[0-3]\]/.test(finding.title)
      ? finding.title
      : `[P${finding.priority}] ${finding.title}`;
    let body = `${HODOR_REVIEW_MARKER}\n<!-- hodor:finding:${fingerprint} -->\n**${title}**\n\n${finding.body}`;

    if (finding.suggestion) {
      const { start, end } = finding.code_location.line_range;
      const span = Math.max(0, end - start);
      body += `\n\n\`\`\`suggestion:-0+${span}\n${finding.suggestion}\n\`\`\``;
    }

    try {
      await createGitlabDraftNote(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        body,
        parsed.host,
        {
          filePath: relPath,
          line: finding.code_location.line_range.start,
          diffRefs,
        },
      );
      inlineCreated++;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(`inline note for ${finding.title}: ${message}`);
      logger.warn(`Failed to create inline note for "${finding.title}": ${message}`);
      inlineFailed++;
    }
  }

  logger.info(
    `Created ${inlineCreated} inline draft note(s)` +
      `${inlineDeduplicated > 0 ? ` (${inlineDeduplicated} already open)` : ""}` +
      `${inlineFailed > 0 ? ` (${inlineFailed} failed)` : ""}`,
  );

  let draftsPublished = false;
  if (inlineCreated > 0) {
    try {
      await bulkPublishGitlabDraftNotes(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        parsed.host,
      );
      draftsPublished = true;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(`draft publish: ${message}`);
      logger.warn(`Failed to bulk publish draft notes: ${message}`);
    }
  }

  let summaryPosted = false;
  if (reviewStyle === "hybrid" || review.findings.length === 0) {
    let summaryBody = renderSummaryMarkdown(review);
    if (headSha) summaryBody = `<!-- hodor:sha:${headSha} -->\n${summaryBody}`;
    if (model) summaryBody += `\n---\n\nReview generated by Hodor (model: \`${model}\`)`;
    if (metricsFooter) summaryBody += `\n\n${metricsFooter}`;
    try {
      await postGitlabMrComment(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        summaryBody,
        parsed.host,
      );
      summaryPosted = true;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(`summary comment: ${message}`);
      logger.warn(`Failed to post summary comment: ${message}`);
    }
  }

  let commitStatusPosted = false;
  if (commitStatus) {
    try {
      await postGitlabReviewCommitStatus(parsed, review, diffRefs);
      commitStatusPosted = true;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(`commit status: ${message}`);
      logger.warn(`Failed to post commit status: ${message}`);
    }
  }

  let reconciledDiscussions = 0;
  const baseDeliveryComplete =
    reviewStyle === "hybrid"
      ? summaryPosted && inlineFailed === 0 && (inlineCreated === 0 || draftsPublished)
      : inlineFailed === 0 &&
        (review.findings.length === 0 ? summaryPosted : inlineCreated === 0 || draftsPublished);

  if (reconcileDiscussions && baseDeliveryComplete) {
    const currentFingerprints = new Set(
      review.findings.map((finding) => getFindingFingerprint(finding, workspacePath)),
    );
    const staleDiscussionIds = [...existingByFingerprint.entries()]
      .filter(([fingerprint]) => !currentFingerprints.has(fingerprint))
      .flatMap(([, ids]) => [...ids]);
    if (staleDiscussionIds.length > 0) {
      reconciledDiscussions = await resolveGitlabDiscussions(
        parsed.owner,
        parsed.repo,
        parsed.prNumber,
        staleDiscussionIds,
        parsed.host,
      );
      if (reconciledDiscussions !== staleDiscussionIds.length) {
        errors.push(
          `discussion reconciliation: resolved ${reconciledDiscussions}/${staleDiscussionIds.length}`,
        );
      }
    }
  }

  const success =
    baseDeliveryComplete &&
    (!commitStatus || commitStatusPosted) &&
    (!reconcileDiscussions || !errors.some((error) => error.startsWith("discussion ")));

  return {
    success,
    platform: "gitlab",
    mrNumber: parsed.prNumber,
    error: success ? undefined : errors[0] ?? "Review delivery was incomplete",
    errors,
    summaryPosted,
    inlineCreated,
    inlineFailed,
    draftsPublished,
    commitStatusPosted,
    reconciledDiscussions,
  };
}
